name: Client Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Inject API Key into built file
        run: |
          sed -i "s|MABINOGI_API_KEY|${{ secrets.MABINOGI_API_KEY }}|g" script/알반.js

      - name: Verify replacement in 알반.js
        run: cat script/알반.js

      - name: Prepare deployment artifact
        run: |
          rm -rf docs
          rsync -av --exclude='.git' . docs

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
