name: client

on:
  push:
    branches:
      - main  # 또는 배포를 원하는 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Inject API Key into built file
        run: |
          sed -i "s/MABINOGI_API_KEY/${{vars.MABINOGI_API_KEY}}/g" script/알반.js

      - name: Verify replacement in 알반.js
        run: cat script/알반.js

      - name: Prepare deployment artifact
        run: |
          # 빌드 산출물이 "build" 폴더에 생성되었다고 가정하고, 이를 "docs" 폴더로 옮깁니다.
          rm -rf docs
          rsync -av --exclude='.git' . docs
